blueprint:
  name: "HASP Theme Light on Dark"
  description: |

    ## Description

    Press EXECUTE to apply the theme Light on Dark to the selected HASP device

    ![Preview](https://raw.githubusercontent.com/HASwitchPlate/Blueprints/main/images/hasp_Theme_Light_on_Dark.png?raw=true)

  source_url: "https://github.com/HASwitchPlate/Blueprints/blob/main/hasp_Theme_Light_on_Dark.yaml"
  domain: automation
  input:
    haspconnected:
      name: "HASP Device"
      description: "Select the HASP device"
      selector:
        entity:
          integration: mqtt
          domain: binary_sensor
          device_class: connectivity

mode: single
max_exceeded: silent

variables:
  haspconnected: !input haspconnected
  haspname: '{{ haspconnected.split(".")[1].split("_connected")[0] }}'
  selected_foreground_brightness: "255"
  selected_foreground_color: "[255, 255, 255]"
  selected_background_brightness: "1"
  selected_background_color: "[255, 255, 255]"
  unselected_foreground_brightness: "224"
  unselected_foreground_color: "[255, 255, 255]"
  unselected_background_brightness: "64"
  unselected_background_color: "[255, 255, 255]"

trigger: []

action:
  - service: light.turn_on
    data:
      entity_id: "light.{{haspname}}_selected_foreground_color"
      rgb_color: "{{selected_foreground_color}}"
  - service: light.turn_on
    data:
      entity_id: "light.{{haspname}}_selected_foreground_color"
      brightness: "{{selected_foreground_brightness}}"
  - service: light.turn_on
    data:
      entity_id: "light.{{haspname}}_selected_background_color"
      rgb_color: "{{selected_background_color}}"
  - service: light.turn_on
    data:
      entity_id: "light.{{haspname}}_selected_background_color"
      brightness: "{{selected_background_brightness}}"
  - service: light.turn_on
    data:
      entity_id: "light.{{haspname}}_unselected_foreground_color"
      rgb_color: "{{unselected_foreground_color}}"
  - service: light.turn_on
    data:
      entity_id: "light.{{haspname}}_unselected_foreground_color"
      brightness: "{{unselected_foreground_brightness}}"
  - service: light.turn_on
    data:
      entity_id: "light.{{haspname}}_unselected_background_color"
      rgb_color: "{{unselected_background_color}}"
  - service: light.turn_on
    data:
      entity_id: "light.{{haspname}}_unselected_background_color"
      brightness: "{{unselected_background_brightness}}"
